{
 "title": "AzSlurm Cluster Dashboard",
 "description": "Slurm Cluster Overview Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Subscription",
    "label": "Subscription",
    "query": {
     "query": "label_values(jetpack_cluster_info,subscription)"
    }
   },
   { "name": "promDatasource", "label": "Prometheus Data Source", "query": "prometheus" },
   {
    "name": "partition",
    "query": {
     "query": "label_values(azslurm_partition_info, partition)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(jetpack_cluster_info, cluster)"
    }
   }
  ]
 },
 "panels": [
  { "type": "library-panel-ref", "gridPos": { "h": 3, "w": 13, "x": 0, "y": 0 } },
  { "type": "library-panel-ref", "gridPos": { "h": 3, "w": 11, "x": 13, "y": 0 } },
  { "title": "Slurm Cluster Health Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Slurm Scheduler Health",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sdiag_main_cycle_time_us{type=\"mean\",cluster=\"$cluster\"}",
     "legendFormat": "Mean Scheduler Cycle (µs)"
    },
    {
     "expr": "sdiag_main_mean_depth_cycle{cluster=\"$cluster\"}",
     "legendFormat": "Mean Depth Cycle"
    },
    {
     "expr": "sdiag_server_thread_count{cluster=\"$cluster\"}",
     "legendFormat": "Controller Threads"
    },
    {
     "expr": "sdiag_agent_queue_size{cluster=\"$cluster\"}",
     "legendFormat": "Agent Queue"
    },
    {
     "expr": "sdiag_dbd_agent_queue_size{cluster=\"$cluster\"}",
     "legendFormat": "DBD Queue"
    },
    {
     "expr": "sum(squeue_partition_jobs_state{cluster=\"$cluster\",partition=~\"$partition\", state=\"pending\"} or vector(0))",
     "legendFormat": "Queue Pressure"
    },
    {
     "expr": "floor(increase(\r\n  sum(sacct_terminal_jobs_total{cluster=\"$cluster\",partition=~\"$partition\",state!=\"completed\"} or vector(0))[24h:$__interval]\r\n))",
     "legendFormat": "Failed Jobs (Today)"
    }
   ]
  },
  {
   "title": "Active Cluster Utilization %",
   "type": "stat",
   "description": "#of of allocated nodes over all powered up nodes",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  (sum(sinfo_partition_nodes_state{cluster=\"$cluster\", partition=~\"$partition\", state=~\"allocated|mixed|draining\"}) or vector(0))\r\n  /\r\n  (\r\n    sum(sinfo_partition_nodes_state{cluster=\"$cluster\", partition=~\"$partition\"})\r\n    -\r\n    sum(sinfo_partition_nodes_state{cluster=\"$cluster\", partition=~\"$partition\", state=~\"powered_off\"} or vector(0))\r\n  )\r\n) * 100\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Cluster Utilization %",
   "type": "stat",
   "description": "#of of allocated nodes over all available nodes",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  (sum(sinfo_partition_nodes_state{cluster=\"$cluster\", partition=~\"$partition\", state=~\"allocated|mixed|draining\"}) or vector(0))\r\n  /\r\n  (\r\n    sum(sinfo_partition_nodes_state{cluster=\"$cluster\", partition=~\"$partition\"})\r\n\r\n  )\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finished Jobs between $__from and $__to",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(\r\n  sum(sacct_terminal_jobs_total{cluster=\"$cluster\",partition=~\"$partition\",state!=\"completed\"} or vector(0))[$__range:$__interval]\r\n))",
     "legendFormat": "Failed Jobs"
    },
    {
     "expr": "floor(increase(\r\n  sum(sacct_terminal_jobs_total{cluster=\"$cluster\",partition=~\"$partition\",state=\"completed\"} or vector(0))[$__range:$__interval]\r\n))",
     "legendFormat": "Completed Jobs"
    },
    {
     "expr": "floor(increase(\r\n  sum(sacct_terminal_jobs_total{cluster=\"$cluster\",partition=~\"$partition\"} or vector(0))[$__range:$__interval]\r\n))",
     "legendFormat": "Finished Jobs"
    }
   ]
  },
  {
   "title": "Cluster Specs",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "jetpack_cluster_info{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodelist by State",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 12 },
   "targets": [
    {
     "expr": "sinfo_partition_nodes_state{cluster=\"$cluster\",partition=~\"$partition\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Nodes by Partition $partition",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster)(sinfo_partition_nodes_state{cluster=\"$cluster\"})",
     "legendFormat": "Total Slurm Nodes"
    },
    {
     "expr": "sum by (partition)(sinfo_partition_nodes_state{cluster=\"$cluster\",partition=~\"$partition\"})",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 18 },
   "options": {
    "content": "**Note:** Finished Jobs panel requires Slurm accounting to be enabled in the cluster. Panel will not populate if accounting is disabled."
   }
  },
  { "title": "README", "type": "library-panel-ref", "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 } }
 ]
}