{
 "title": "AzSlurm Job and Node Status Dashboard",
 "description": "Slurm Cluster Job and Node Status Overview Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Subscription",
    "label": "Subscription",
    "query": {
     "query": "label_values(jetpack_cluster_info,subscription)"
    }
   },
   { "name": "promDatasource", "label": "Prometheus Data Source", "query": "prometheus" },
   {
    "name": "partition",
    "query": {
     "query": "label_values(azslurm_partition_info, partition)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(jetpack_cluster_info, cluster)"
    }
   }
  ]
 },
 "panels": [
  { "type": "library-panel-ref", "gridPos": { "h": 3, "w": 13, "x": 0, "y": 0 } },
  { "type": "library-panel-ref", "gridPos": { "h": 3, "w": 11, "x": 13, "y": 0 } },
  {
   "title": "Job and Node Status Overview for partition $partition",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }
  },
  {
   "title": "squeue snapshot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(squeue_partition_jobs_state{cluster=\"$cluster\",partition=~\"$partition\", state=\"pending\"} or vector(0))",
     "legendFormat": "pending"
    },
    {
     "expr": "sum by (state)(squeue_partition_jobs_state{cluster=\"$cluster\",partition=~\"$partition\", state!=\"pending\"})",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum(label_replace(squeue_partition_jobs_state{cluster=\"$cluster\",partition=~\"$partition\"}, \"total\", \"Submitted Jobs\", \"\", \"\") or vector(0))",
     "legendFormat": "Submitted Jobs"
    }
   ]
  },
  {
   "title": "Live: Node status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (state)(sinfo_partition_nodes_state{cluster=\"$cluster\",partition=~\"$partition\", state!=\"n/a\"})",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum by (cluster)(sinfo_partition_nodes_state{cluster=\"$cluster\",partition=~\"$partition\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Job Queue Overview by State",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (state)(squeue_partition_jobs_state{cluster=\"$cluster\",partition=~\"$partition\", state!=\"pending\"})",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum(squeue_partition_jobs_state{cluster=\"$cluster\",partition=~\"$partition\", state=\"pending\"} or vector(0))",
     "legendFormat": "pending"
    },
    {
     "expr": "sum(label_replace(squeue_partition_jobs_state{cluster=\"$cluster\",partition=~\"$partition\"}, \"total\", \"Submitted Jobs\", \"\", \"\") or vector(0))",
     "legendFormat": "submitted"
    }
   ]
  },
  {
   "title": "Live: Node status",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by (state)(sinfo_partition_nodes_state{cluster=\"$cluster\",partition=~\"$partition\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Main Scheduling Cycle Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sdiag_main_cycle_time_us{cluster=\"$cluster\",type=\"last\"}",
     "legendFormat": "Last Cycle"
    },
    {
     "expr": "sdiag_main_cycle_time_us{cluster=\"$cluster\",type=\"mean\"}",
     "legendFormat": "Mean Cycle"
    },
    {
     "expr": "sdiag_main_cycle_time_us{cluster=\"$cluster\",type=\"max\"}",
     "legendFormat": "Max Cycle"
    }
   ]
  },
  { "title": "README", "type": "library-panel-ref", "gridPos": { "h": 4, "w": 24, "x": 0, "y": 40 } }
 ]
}