{
 "title": "AzSlurm Extra Details Dashboard",
 "description": "Slurm Cluster Nodelist and Partition Specs Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Subscription",
    "label": "Subscription",
    "query": {
     "query": "label_values(jetpack_cluster_info,subscription)"
    }
   },
   { "name": "promDatasource", "label": "Prometheus Data Source", "query": "prometheus" },
   {
    "name": "partition",
    "query": {
     "query": "label_values(azslurm_partition_info, partition)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(jetpack_cluster_info, cluster)"
    }
   },
   {
    "name": "slurm_cluster",
    "query": {
     "query": "SELECT SUBSTRING_INDEX('$cluster', '/', -1)"
    }
   },
   { "name": "mysqlDatasource", "label": "MySQL Datasource", "query": "mysql" },
   {
    "name": "cluster_db",
    "label": "Cluster database",
    "query": {
     "query": "SELECT CONCAT(REPLACE(SUBSTRING_INDEX('$cluster', '/', -1), '-', '_'), '_acct_db')"
    }
   }
  ]
 },
 "panels": [
  { "type": "library-panel-ref", "gridPos": { "h": 3, "w": 13, "x": 0, "y": 0 } },
  { "type": "library-panel-ref", "gridPos": { "h": 3, "w": 11, "x": 13, "y": 0 } },
  { "title": "Extra Cluster Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Current Running Jobs between $__from and $__to",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    j.id_job as \"jobid\",\r\n    j.job_name,\r\n    j.`partition`,\r\n    a.`user` as \"user\",\r\n    j.nodelist,\r\n    j.nodes_alloc,\r\n    j.cpus_req,\r\n    CASE (j.state & 0xff)\r\n        WHEN 0 THEN 'PENDING'\r\n        WHEN 1 THEN 'RUNNING'\r\n        WHEN 2 THEN 'SUSPENDED'\r\n        WHEN 3 THEN 'COMPLETED'\r\n        WHEN 4 THEN 'CANCELLED'\r\n        WHEN 5 THEN 'FAILED'\r\n        WHEN 6 THEN 'TIMEOUT'\r\n        WHEN 7 THEN 'NODE_FAIL'\r\n        WHEN 8 THEN 'PREEMPTED'\r\n        WHEN 9 THEN 'BOOT_FAIL'\r\n        WHEN 10 THEN 'DEADLINE'\r\n        WHEN 11 THEN 'OUT_OF_MEMORY'\r\n        ELSE 'UNKNOWN'\r\n    END as \"state\",\r\n   \r\n    FROM_UNIXTIME(j.time_submit) as \"submit_time\",\r\n    FROM_UNIXTIME(j.time_start) as \"start_time\"\r\nFROM \r\n    ${cluster_db}.`${slurm_cluster}_job_table` j\r\nLEFT JOIN \r\n    ${cluster_db}.`${slurm_cluster}_assoc_table` a ON j.id_assoc = a.id_assoc\r\nWHERE \r\n    (j.state & 0xff) = 1\r\n    AND $__unixEpochFilter(j.time_start)\r\n    AND j.`partition` IN (${partition:singlequote})\r\nORDER BY \r\n    j.time_start DESC\r\nLIMIT 1000"
    }
   ]
  },
  {
   "title": "Job History between $__from and $__to",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    j.id_job as \"jobid\",\r\n    j.job_name,\r\n    j.`partition`,\r\n    a.`user` as \"user\",\r\n    j.nodelist,\r\n    j.nodes_alloc,\r\n    j.cpus_req,\r\n    CASE (j.state & 0xff)\r\n        WHEN 0 THEN 'PENDING'\r\n        WHEN 1 THEN 'RUNNING'\r\n        WHEN 2 THEN 'SUSPENDED'\r\n        WHEN 3 THEN 'COMPLETED'\r\n        WHEN 4 THEN 'CANCELLED'\r\n        WHEN 5 THEN 'FAILED'\r\n        WHEN 6 THEN 'TIMEOUT'\r\n        WHEN 7 THEN 'NODE_FAIL'\r\n        WHEN 8 THEN 'PREEMPTED'\r\n        WHEN 9 THEN 'BOOT_FAIL'\r\n        WHEN 10 THEN 'DEADLINE'\r\n        WHEN 11 THEN 'OUT_OF_MEMORY'\r\n        ELSE 'UNKNOWN'\r\n    END as \"state\",\r\n    CONCAT((j.exit_code >> 8) & 0xff, ':', j.exit_code & 0xff) as \"exit_code\",\r\n    CASE CONCAT((j.exit_code >> 8) & 0xff, ':', j.exit_code & 0xff)\r\n        WHEN '0:0' THEN ' '\r\n        WHEN '1:0' THEN 'General failure'\r\n        WHEN '2:0' THEN 'Misuse of shell built-in'\r\n        WHEN '125:0' THEN 'Slurm Out of Memory Error'\r\n        WHEN '126:0' THEN 'Command invoked cannot execute'\r\n        WHEN '127:0' THEN 'Command not found'\r\n        WHEN '128:0' THEN 'Invalid argument to exit'\r\n        WHEN '129:0' THEN 'SIGHUP'\r\n        WHEN '130:0' THEN 'SIGINT - Ctrl+C'\r\n        WHEN '131:0' THEN 'SIGQUIT'\r\n        WHEN '134:0' THEN 'SIGABRT'\r\n        WHEN '137:0' THEN 'SIGKILL - Force killed'\r\n        WHEN '139:0' THEN 'SIGSEGV - Segfault'\r\n        WHEN '141:0' THEN 'SIGPIPE'\r\n        WHEN '143:0' THEN 'SIGTERM - Terminated'\r\n        WHEN '152:0' THEN 'SIGXCPU - CPU limit'\r\n        WHEN '153:0' THEN 'SIGXFSZ - File size limit'\r\n        ELSE ''\r\n    END as \"reason\",\r\n    FROM_UNIXTIME(j.time_submit) as \"submit_time\",\r\n    FROM_UNIXTIME(j.time_start) as \"start_time\",\r\n    FROM_UNIXTIME(j.time_end) as \"end_time\"\r\nFROM \r\n    ${cluster_db}.`${slurm_cluster}_job_table` j\r\nLEFT JOIN \r\n    ${cluster_db}.`${slurm_cluster}_assoc_table` a ON j.id_assoc = a.id_assoc\r\nWHERE \r\n    $__unixEpochFilter(j.time_end)\r\n    AND j.`partition` IN (${partition:singlequote})\r\nORDER BY \r\n    j.time_end DESC\r\nLIMIT 1000"
    }
   ]
  },
  {
   "title": "Nodelist by State",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sinfo_partition_nodes_state{cluster=\"$cluster\",partition=~\"$partition\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Specs",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "azslurm_partition_info{cluster=\"$cluster\",partition=~\"$partition\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "README", "type": "library-panel-ref", "gridPos": { "h": 4, "w": 24, "x": 0, "y": 41 } }
 ]
}