{
 "title": "AzSlurm Dashboard",
 "description": "Slurm Cluster Mission Control Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Subscription",
    "label": "Subscription",
    "query": {
     "query": "label_values(jetpack_cluster_info,subscription)"
    }
   },
   { "name": "promDatasource", "label": "Prometheus Data Source", "query": "prometheus" },
   {
    "name": "partition",
    "query": {
     "query": "label_values(azslurm_partition_info, partition)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(jetpack_cluster_info, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Overview for partition $partition",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "squeue snapshot",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (state)(squeue_partition_jobs_state{cluster=\"$cluster\",partition=~\"$partition\"})",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum by (cluster)(label_replace(squeue_partition_jobs_state{cluster=\"$cluster\",partition=~\"$partition\"}, \"total\", \"Submitted Jobs\", \"\", \"\"))",
     "legendFormat": "Submitted Jobs"
    }
   ]
  },
  {
   "title": "Job Queue Overview by State",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 10, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "sum by (state)(squeue_partition_jobs_state{cluster=\"$cluster\",partition=~\"$partition\"})",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum by (cluster)(label_replace(squeue_partition_jobs_state{cluster=\"$cluster\",partition=~\"$partition\"}, \"total\", \"Submitted Jobs\", \"\", \"\"))",
     "legendFormat": "submitted"
    }
   ]
  },
  {
   "title": "Active Cluster Utilization %",
   "type": "stat",
   "description": "#of of allocated nodes over all powered up nodes",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  (sum(sinfo_partition_nodes_state{cluster=\"$cluster\", partition=~\"$partition\", state=~\"allocated|mixed|draining\"}) or vector(0))\r\n  /\r\n  (\r\n    sum(sinfo_partition_nodes_state{cluster=\"$cluster\", partition=~\"$partition\"})\r\n    -\r\n    sum(sinfo_partition_nodes_state{cluster=\"$cluster\", partition=~\"$partition\", state=~\"powered_off\"})\r\n  )\r\n) * 100\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Cluster Utilization %",
   "type": "stat",
   "description": "#of of allocated nodes over all available nodes",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  (sum(sinfo_partition_nodes_state{cluster=\"$cluster\", partition=~\"$partition\", state=~\"allocated|mixed|draining\"}) or vector(0))\r\n  /\r\n  (\r\n    sum(sinfo_partition_nodes_state{cluster=\"$cluster\", partition=~\"$partition\"})\r\n\r\n  )\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Jobs by Node Allocation",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "topk(10,squeue_job_nodes_allocated{cluster=\"$cluster\",partition=~\"$partition\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finished Jobs between $__from and $__to",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(\r\n  sum(sacct_terminal_jobs_total{cluster=\"$cluster\",partition=~\"$partition\",state!=\"completed\"} or vector(0))[$__range:$__interval]\r\n))",
     "legendFormat": "Failed Jobs"
    },
    {
     "expr": "floor(increase(\r\n  sum(sacct_terminal_jobs_total{cluster=\"$cluster\",partition=~\"$partition\",state=\"completed\"} or vector(0))[$__range:$__interval]\r\n))",
     "legendFormat": "Completed Jobs"
    },
    {
     "expr": "floor(increase(\r\n  sum(sacct_terminal_jobs_total{cluster=\"$cluster\",partition=~\"$partition\"} or vector(0))[$__range:$__interval]\r\n))",
     "legendFormat": "Finished Jobs"
    }
   ]
  },
  {
   "title": "Live: Node status",
   "type": "stat",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (state)(sinfo_partition_nodes_state{cluster=\"$cluster\",partition=~\"$partition\", state!=\"n/a\"})",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum by (cluster)(sinfo_partition_nodes_state{cluster=\"$cluster\",partition=~\"$partition\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Live: Node status",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 10, "x": 9, "y": 17 },
   "targets": [
    {
     "expr": "sum by (state)(sinfo_partition_nodes_state{cluster=\"$cluster\",partition=~\"$partition\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 25 },
   "options": {
    "content": "**Note:** Finished Jobs panel requires Slurm accounting to be enabled in the cluster. Panel will not populate if accounting is disabled."
   }
  },
  {
   "title": "Nodelist by State",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sinfo_partition_nodes_state{cluster=\"$cluster\",partition=~\"$partition\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster Specs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Cluster Specs",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "jetpack_cluster_info{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Nodes by Partition $partition",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 10, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster)(sinfo_partition_nodes_state{cluster=\"$cluster\"})",
     "legendFormat": "Total Slurm Nodes"
    },
    {
     "expr": "sum by (partition)(sinfo_partition_nodes_state{cluster=\"$cluster\",partition=~\"$partition\"})",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Partition Specs",
   "type": "table",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "azslurm_partition_info{cluster=\"$cluster\",partition=~\"$partition\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "README",
   "type": "text",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 53 },
   "options": {
    "content": "## Disclaimer\n\n> **⚠️ Note:** Under heavy system load, dashboards may update more slowly. Displayed metrics may experience delays and should not be relied upon as a real-time source of truth during peak activity. Gaps in the dashboard may be seen when azslurm-exporter is down or when slurmctld is down."
   }
  }
 ]
}