{
 "title": "SLURM Dashboard",
 "description": "Slurm Cluster Mission Control Dashboard",
 "time": { "from": "2026-01-21T17:34:33.742Z", "to": "2026-01-21T17:48:25.165Z" },
 "templating": {
  "list": [
   {
    "name": "username",
    "query": {
     "query": "label_values(slurm_user_jobs, username)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(slurm_account_jobs,instance)"
    }
   },
   {
    "name": "Subscription",
    "label": "Subscription",
    "query": {
     "query": "label_values(slurm_account_jobs,subscription)"
    }
   },
   { "name": "promDatasource", "label": "Prometheus Data Source", "query": "prometheus" },
   {
    "name": "partition",
    "query": {
     "query": "label_values(slurm_partition_jobs_running, partition)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(slurm_node_cpus, node)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_cpu_seconds_total, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Overview for partion $partition",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "squeue snapshot",
   "type": "stat",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (state) (\r\n  label_replace(slurm_partition_jobs_running{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"Running Jobs\", \"\", \"\") or\r\n  label_replace(slurm_partition_jobs_configuring{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"Configuring Jobs\", \"\", \"\") or \r\n  label_replace(slurm_partition_jobs_pending{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"Pending Jobs\", \"\", \"\") or \r\n  label_replace(slurm_partition_jobs_failed{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"Failed Jobs\", \"\", \"\") or \r\n  label_replace(slurm_partition_jobs_cancelled{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"Cancelled Jobs\", \"\", \"\") or\r\n  label_replace(slurm_partition_jobs_node_failed{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"Node Failed Jobs\", \"\", \"\") or\r\n  label_replace(slurm_partition_jobs_suspended{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"Suspended Jobs\", \"\", \"\") or\r\n  label_replace(slurm_partition_jobs_timeout{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"Timed Out Jobs\", \"\", \"\") or\r\n  label_replace(slurm_partition_jobs_preempted{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"Preempted Jobs\", \"\", \"\") or \r\n  label_replace(slurm_partition_jobs{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"Submitted Jobs\", \"\", \"\")\r\n\r\n\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job State Overview",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "sum by (state) (\r\n  label_replace(slurm_partition_jobs_running{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"Running Jobs\", \"\", \"\") or\r\n  label_replace(slurm_partition_jobs_configuring{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"Configuring Jobs\", \"\", \"\") or\r\n  label_replace(slurm_partition_jobs_pending{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"Pending Jobs\", \"\", \"\") or \r\n  label_replace(slurm_partition_jobs_failed{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"Failed Jobs\", \"\", \"\") or \r\n  label_replace(slurm_partition_jobs_cancelled{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"Cancelled Jobs\", \"\", \"\") or\r\n  label_replace(slurm_partition_jobs_node_failed{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"Node Failed Jobs\", \"\", \"\") or\r\n  label_replace(slurm_partition_jobs_suspended{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"Suspended Jobs\", \"\", \"\") or\r\n  label_replace(slurm_partition_jobs_timeout{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"Timed Out Jobs\", \"\", \"\") or\r\n  label_replace(slurm_partition_jobs_preempted{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"Preempted Jobs\", \"\", \"\") or \r\n  label_replace(slurm_partition_jobs{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"Submitted Jobs\", \"\", \"\")\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live: Node status",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (state) (\r\n  label_replace(slurm_partition_nodes_idle{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"IDLE\", \"\", \"\") or\r\n  label_replace(slurm_partition_nodes_alloc{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"ALLOCATED\", \"\", \"\") or\r\n  label_replace(slurm_partition_nodes_down{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"DOWN\", \"\", \"\") or\r\n  label_replace(slurm_partition_nodes_drain{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"DRAINING\", \"\", \"\") or\r\n  label_replace(slurm_partition_nodes_maint{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"MAINTENANCE\", \"\", \"\") or\r\n  label_replace(slurm_partition_nodes_fail{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"FAIL\", \"\", \"\") or\r\n  label_replace(slurm_partition_nodes_resv{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"RESERVED\", \"\", \"\") or\r\n  label_replace(slurm_partition_nodes_powered_down{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"POWERED DOWN\", \"\", \"\") or \r\n  label_replace(slurm_partition_nodes_power_down{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"POWERING DOWN\", \"\", \"\") or\r\n  label_replace(slurm_partition_nodes_noresp{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"UNRESPONSIVE\", \"\", \"\") or \r\n  label_replace(slurm_partition_nodes_powering_up{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"POWERING UP\", \"\", \"\")\r\n  \r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live: Node status",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 9, "x": 10, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (state) (\r\n  label_replace(slurm_partition_nodes_alloc{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"ALLOCATED\", \"\", \"\") or\r\n  label_replace(slurm_partition_nodes_down{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"DOWN\", \"\", \"\") or\r\n  label_replace(slurm_partition_nodes_drain{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"DRAINING\", \"\", \"\") or\r\n  label_replace(slurm_partition_nodes_maint{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"MAINTENANCE\", \"\", \"\") or\r\n  label_replace(slurm_partition_nodes_fail{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"FAIL\", \"\", \"\") or\r\n  label_replace(slurm_partition_nodes_resv{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"RESERVED\", \"\", \"\") or\r\n  label_replace(slurm_partition_nodes_power_down{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"POWERING DOWN\", \"\", \"\") or\r\n  label_replace(slurm_partition_nodes_noresp{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"UNRESPONSIVE\", \"\", \"\") or \r\n  label_replace(slurm_partition_nodes_powering_up{cluster=\"$cluster\",partition=~\"$partition\"} != 0, \"state\", \"POWERING UP\", \"\", \"\")\r\n  \r\n)",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Total Slurm Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (slurm_partition_nodes{partition=~\"$partition\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Nodes by Partition",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (partition)(slurm_partition_nodes{partition=~\"$partition\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}